### ISSUE TITLE
References to missing assets /webfonts/fa-solid-900.woff

### ISSUE THREAD

**Issue by cassidydotdk** [ppoffice/hexo-theme-icarus#335]
Please make sure these boxes are checked before submitting your issue. Thank you!

- [X] I have setuped and configurated the blog according to [Hexo official documentation](https://hexo.io/);
- [X] I have read the [Theme Wiki](https://github.com/ppoffice/hexo-theme-icarus/wiki) carefully and created my own configuration file(_config.yml);
- [X] I have looked up the [Issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no duplicate issues.

I've installed the latest version of the theme in my newly set up Hexo blog. It works - but there are some minor issues with some of the webfont assets. I basically get 4 errors when loading up the front page.

![image](https://user-images.githubusercontent.com/8483909/42605197-f35fc5b0-8576-11e8-8bb4-7a9ccaa0bd49.png)

`hexo generate` and `hexo deploy` generate no errors.  It seems to me that the `.woff2` files that are reported missing should be referenced via `/libs/fontawesome5` and not `/webfonts`, but to my knowledge, this is controlled entirely within the theme?

URL to the test blog: https://intothecloud.blog/ (currently fixed most of the problems by rolling back to an earlier commit)

**Comment by ppoffice** [comment]
@cassidydotdk The latest commit should fix the "resource not found" issue. However, the RSS icon in the profile panel will remain invalid as it is not in the FontAwesome Brand icon set, which is used by social links.

**Comment by cassidydotdk** [comment]
Thanks a lot :D   RSS icon I can live without, I just used it on a previous version of this theme.

One load error remains - but I'm not 100% certain this comes from Icarus or something else. 

![image](https://user-images.githubusercontent.com/8483909/42645258-e192258a-85fd-11e8-90dd-05d1825ecc14.png)

**Comment by ppoffice** [comment]
@cassidydotdk 
Is it caused by Adblock?
https://issues.adblockplus.org/ticket/6744

**Comment by cassidydotdk** [comment]
Hmm. It does look like a related issue. But I disabled it, and still see the same thing. And as I said, not sure if this is Icarus or Hexo or something else entirely.

![image](https://user-images.githubusercontent.com/8483909/42646959-bc8aaf78-8602-11e8-920a-192641215df5.png)

I tried raising it on Hexo, to see if anyone had a clue. https://github.com/hexojs/hexo/issues/3209
